apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-baseline-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-repo.git' # Thay bằng link Git chứa code
    targetRevision: main
    path: baseline-policies # Trỏ vào thư mục chứa Kyverno Policies
  destination:
    server: 'https://kubernetes.default.svc' # Triển khai trên chính cụm nội bộ
    namespace: default # ClusterPolicy là tài nguyên cấp cụm nên namespace ở đây không quá quan trọng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Tự động phục hồi nếu ai đó sửa tay trên Cluster
