apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-clone-secrets
spec:
  rules:
  - name: clone-registry-secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: Secret
      name: my-registry-secret
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: default
        name: my-registry-secret
